kind: Template
apiVersion: v1
metadata:
  name: "registry-console"
  annotations:
    description: "用于部署registry web console的模板.需要cluster-admin权限."
    tags: infrastructure
labels:
  createdBy: "registry-console-template"
objects:
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: "registry-console"
      labels:
        name: "registry-console"
    spec:
      triggers:
      - type: ConfigChange
      replicas: 1
      selector:
        name: "registry-console"
      template:
        metadata:
          labels:
            name: "registry-console"
        spec:
          containers:
            - name: registry-console
              image: ${IMAGE_NAME}:${IMAGE_VERSION}
              ports:
                - containerPort: 9090
                  protocol: TCP
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /ping
                  port: 9090
                  scheme: HTTP
                initialDelaySeconds: 10
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 5
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /ping
                  port: 9090
                  scheme: HTTP
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 5
              env:
                - name: OPENSHIFT_OAUTH_PROVIDER_URL
                  value: "${OPENSHIFT_OAUTH_PROVIDER_URL}"
                - name: OPENSHIFT_OAUTH_CLIENT_ID
                  value: "${OPENSHIFT_OAUTH_CLIENT_ID}"
                - name: KUBERNETES_INSECURE
                  value: "false"
                - name: COCKPIT_KUBE_INSECURE
                  value: "false"
                - name: REGISTRY_ONLY
                  value: "true"
                - name: REGISTRY_HOST
                  value: "${REGISTRY_HOST}"
  - kind: Service
    apiVersion: v1
    metadata:
     name: "registry-console"
     labels:
       name: "registry-console"
    spec:
      type: ClusterIP
      ports:
        - name: registry-console
          protocol: TCP
          port: 9000
          targetPort: 9090
      selector:
        name: "registry-console"
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: registry-console
      annotations:
        description: Atomic Registry console
    spec:
      tags:
        - annotations: null
          from:
            kind: DockerImage
            name: ${IMAGE_NAME}:${IMAGE_VERSION}
          name: ${IMAGE_VERSION}
  - kind: OAuthClient
    apiVersion: v1
    metadata:
      name: "${OPENSHIFT_OAUTH_CLIENT_ID}"
      respondWithChallenges: false
    secret: "${OPENSHIFT_OAUTH_CLIENT_SECRET}"
    redirectURIs:
      - "${COCKPIT_KUBE_URL}"
parameters:
  - description: "镜像名称"
    name: IMAGE_NAME
    value: "cockpit/kubernetes"
  - description: '镜像版本;比如 对于 "cockpit/kubernetes:latest", 设置版本为 "latest"'
    name: IMAGE_VERSION
    value: latest
  - description: "Openshift OAuth Provider的公共URL, 比如 https://openshift.example.com:8443"
    name: OPENSHIFT_OAUTH_PROVIDER_URL
    required: true
  - description: "Registry console URL. 需要事先通过命令 'oc create route passthrough --service registry-console --port registry-console -n default' 创建, 比如: https://registry-console-default.example.com"
    name: COCKPIT_KUBE_URL
    required: true
  - description: "Oauth客户端秘钥"
    name: OPENSHIFT_OAUTH_CLIENT_SECRET
    from: "user[a-zA-Z0-9]{64}"
    generate: expression
  - description: "Oauth客户端ID"
    name: OPENSHIFT_OAUTH_CLIENT_ID
    value: "cockpit-oauth-client"
  - description: "通过路由暴露的所集成的registry主机名, 比如 registry.example.com"
    name: REGISTRY_HOST
    required: true
