---
- name: Metrics Install Checkpoint Start
  hosts: all
  gather_facts: false
  tasks:
  - name: Set Metrics install 'In Progress'
    run_once: true
    set_stats:
      data:
        installer_phase_metrics:
          title: "Metrics Install"
          playbook: "playbooks/openshift-metrics/config.yml"
          status: "In Progress"
          start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

- name: Ensure that metriics storage path exists and permissions are correct
  hosts: oo_infras_to_config
  gather_facts: false
  tasks:
  - when:
    - openshift_metrics_cassandra_storage_type == "hostmount"
    block:
    - name: Create es storage directory
      file:
        path: "{{ openshift_metrics_cassandra_hostmount_path }}"
        state: directory
        mode: 0777

- name: OpenShift Metrics
  hosts: oo_first_master
  roles:
  - role: openshift_metrics

- name: Metrics Install Checkpoint End
  hosts: all
  gather_facts: false
  tasks:
  - name: Set Metrics install 'Complete'
    run_once: true
    set_stats:
      data:
        installer_phase_metrics:
          status: "Complete"
          end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
