---
- name: Check control node to see if htpasswd is installed
  local_action: command which htpasswd
  register: htpasswd_check
  failed_when: no
  changed_when: no
  become: false

- fail: msg="'htpasswd' is unavailable. Please install httpd-tools on the control node"
  when: htpasswd_check.rc  == 1

- name: Check control node to see if keytool is installed
  local_action: command which keytool
  register: keytool_check
  failed_when: no
  changed_when: no
  become: false

- fail: msg="'keytool' is unavailable. Please install java-1.8.0-openjdk-headless on the control node"
  when: keytool_check.rc  == 1

- include_tasks: generate_certificates.yaml
- include_tasks: generate_serviceaccounts.yaml
- include_tasks: generate_services.yaml
- include_tasks: generate_rolebindings.yaml

- name: Add scc privileged to cassandra sa
  when: openshift_metrics_cassandra_storage_type == 'hostmount'
  oc_adm_policy_user:
    user: "system:serviceaccount:{{ openshift_metrics_project }}:cassandra"
    namespace: "{{ openshift_metrics_project }}"
    resource_kind: scc
    resource_name: hostmount-anyuid
    state: present
